### ISSUE TITLE
CDN suggestions for increased coverage

### ISSUE THREAD

**Issue by edgrd** [mr-mig/webbooost#15]
Please, consider adding these on next Web Boost releases:

Open Source Software CDN
http://osscdn.com/

Ionic Framework CDN
https://code.ionicframework.com/

thanks

**Comment by mr-mig** [comment]
I am wondering whether there is real benefit of adding ionicframework. 

In general, those assets are used from inside Cordova - so that they are not dowloaded. 
Moreover, there is no way to use the extension on mobile (yet).
