### ISSUE TITLE
Scripts unable to download

### ISSUE THREAD

**Issue by Kreozot** [mr-mig/webbooost#23]
1. Turn Webbooost on
2. Go to [http://jquery.com/download/](http://jquery.com/download/)
3. Click "Download the compressed, production jQuery 1.12.1"
4. Upset
5. Turn Webbooost off and refresh the page
6. ...
7. PROFIT!

**Comment by mr-mig** [comment]
Yeah, it is supposed to work like that :)
You cannot download any sript which is pre-bundled.

**Comment by Kreozot** [comment]
Even if user wants to? Really? So the plugin decides what I'm allowed to do?

**Comment by mr-mig** [comment]
Yes, it's called unobtrusive UX

**Comment by Kreozot** [comment]
you forgot <sarcasm> tag
