### ISSUE TITLE
Blocked analytics breaks https://www.duolingo.com

### ISSUE THREAD

**Issue by kof** [mr-mig/webbooost#39]

**Comment by mr-mig** [comment]
Turn it off for duolingo

**Comment by kof** [comment]
Webboost needs a global setting for turning on/off of a blocker. Webboost is communicated as a tool for boosting the speed, it should not break websites. It turns out lots of websites are broken if webboost is not disabled, though I think the adds blocker feature should be optional. I needed to turn off webboost already lots of times, which makes me constantly think that yet another website is probably broken because of webboost.

**Comment by kof** [comment]
Also you can boost analytics.js too if not already done.

**Comment by mr-mig** [comment]
Was done already, breaks sites as well

**Comment by mr-mig** [comment]
Turning off the blocker won't help. 
Packed scripts will still break sites

**Comment by mr-mig** [comment]
Blocking shit makes web faster :)
