### ISSUE TITLE
FYI: Webbooost's Research on CDN Usage and JS Libs Link is Broken

### ISSUE THREAD

**Issue by IGitSylvia** [mr-mig/webbooost#48]
Hey, Mr. Mig, 

I just wanted to let you know that ever since your changed your pretty url-rewrites from slash to hyphen (or when you changed to Ghost CMS) your [Webbooost's Research on CDN Usage and JS Libraries](http://www.metadevelopment.io/2014/03/cdn-usage-and-javascript-library/) link is currently broken--and perhaps others too. Most users may not care much about the inner mechanisms but developers and power users sure do, don't you think?

I recommended you to a Dev. a friend of mine who (like me and you too right?) love pushing the short and long-tail of tweaks and tech that makes for a "faster Internet" experience. 

Спасибо!

**Comment by mr-mig** [comment]
Thanks for pointing my attention to this!
