### ISSUE TITLE
Instructions for make all

### ISSUE THREAD

**Issue by luisantunes8500** [mr-mig/webbooost#58]
@samlowry
As hard as I try, I keep making mistakes with the dependencies.
Can you help me with the step-by-step?
@samlowry I am also interested in your updated fork

**Comment by samlowry** [comment]
Sssup, bro! I'm updated all frameworks, but couldn't make it up.

Found the creator of initial ver. - he said, he started to redesign all to use typescript and that I have to revert to commit 8cb684553c08dc13f0c8f105a2fcf918fb7e64ab

At that moment I became so tired of trying to understand project structure, so I switched to the other projects.

If you're skilful in git - pls revert to that commit, than apply my updates - you'll get all new libs in the extension. Pls share if you did this, or commit here (I never managed public git repos - if need some my action pls tell), or simply fork my repo.

Cheers!

**Comment by mr-mig** [comment]
@luisantunes8500 @samlowry hey folks, I am sorry for been absent for some time. 
I will revert master to the stable commit so that you can build it.

**Comment by mr-mig** [comment]
@luisantunes8500 @samlowry to update the files, you need to put them to the corresponding versioned folder in `injectees` and add the metadata to `config/reg-config` and `config/hash-config`

**Comment by mr-mig** [comment]
The current master corresponds to `v3.2.4` release
